apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
  - name: redis
    port: 6379

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  serviceName: redis
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
        selector: redis
    spec:
      containers:
      - name: redis
        image: redis:6.2.3
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          runAsUser: 1001
        resources:
          requests:
            cpu: 0.5
            memory: 64Mi
          limits:
            cpu: 1.0
            memory: 512Mi